### ISSUE TITLE
Add beancount-plugin-utils dependency to setup.py

### ISSUE THREAD

**Issue by johannesjh** [Akuukis/beancount_share#4]
Hi, this beancount plugin looks very promising, thank you! May I suggest these fixes/improvements to make it easier to get this plugin working.

1. I think there is a mismatch between code and README. The README provides instructions for loading the beancount_share plugin like this: `plugin "beancount_share" "{}"`. I found that this did not work. I could only load the plugin as follows: `plugin "beancount_share.share" "{}"`. 

2. Missing dependency to beancount_plugin_utils in setup.py. I therefore got the following error `Error importing "beancount_share.share": No module named 'beancount_plugin_utils'`. The problem was easy to work around, of course, by manually installing beancount_plugin_utils.

3. By the way, the [beancount_plugin_utils package description](https://pypi.org/project/beancount-plugin-utils/) links to this homepage https://pypi.org/project/beancount-plugin-utils/ which does not exist or is not publicly accessible. Could you publish this repo as well?

thanks, Johannes

**Comment by Akuukis** [comment]
Thanks! Your comments are very good
1. done - 1130b1acd06879aa73c6f000a84b80a77739c5c0
2. done - e8708af57053258fc689e4969ba2604d3c33b21a
3. done - https://github.com/Akuukis/beancount_plugin_utils

Happy New Year ;)

**Comment by johannesjh** [comment]
thank you, you too! br, Johannes
