### ISSUE TITLE
How to handle other party paying

### ISSUE THREAD

**Issue by egetzner** [Akuukis/beancount_share#5]
This is a great plugin, thank you!

One thing that isn't clear to me yet is what to do if the other party paid. Assuming you go on a shared trip or vacation, and the other person paid for something for which the owner of the ledger should pay a shared part. Here's how I would do it currently:

```
2021-01-01 * "Payee" "Bob paid" #share-Bob
   Assets:Debtors:Bob -100 USD
   Expenses:Drinks
```

this is then transformed into:

```
2021-01-01 * "Payee" "Bob paid"
   Expenses:Drinks       50 USD
   Assets:Debtors:Bob   -50 USD
```
Is this the recommended approach? Or would `Liabilities:Creditors:Bob `be more correct (with Liabilities being negative, Assets being positive)?

```
2021-01-01 * "Payee" "Bob paid" #share-Bob
   Liabilities:Creditors:Bob -100 USD
   Expenses:Drinks
```
turns to

```
2021-01-01 * "Payee" "Bob paid"
   Liabilities:Creditors:Bob -100 USD
   Expenses:Drinks       50 USD
   Assets:Debtors:Bob   50 USD
```

Downside to this is you have two different accounts for the same person. When you share with the same person long-term it's nice to have a single account and just keep track of the balance there.

Thanks!

**Comment by Akuukis** [comment]
@egetzner Hi! I'd suggest to assume that debt and credit are symmetric and automatically clears each other. In such case, feel free to keep it in one account, whichever is the most common use case.
